global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'violations-service'
    static_configs:
      - targets: ['violations-service:8000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # Appwrite services monitoring
  - job_name: 'appwrite'
    static_configs:
      - targets: ['appwrite:80']
    metrics_path: '/v1/health'