global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Changed from localhost

  - job_name: 'violations-engine'
    static_configs:
      - targets: ['violations-engine:8000']  # Match your docker-compose service name
    metrics_path: '/metrics'

  # Add Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']  # We'll add this service

  # Update Elasticsearch config
  - job_name: 'elasticsearch'
    metrics_path: '/_nodes/_local/stats'  # Changed metrics path
    static_configs:
      - targets: ['elasticsearch:9200']
    basic_auth:
      username: 'elastic'
      password: 'elastic123!'

  # Update Appwrite config with authentication
  - job_name: 'appwrite'
    metrics_path: '/v1/health'
    static_configs:
      - targets: ['appwrite:80']